#!/bin/bash

if [ -L $0 ]; then
    L=$(readlink $0)
    O=$(dirname $L)
    cd $O
else
    cd $(dirname $0)
fi
. config

if [ ! -f ./docker-compose.yml ]; then
    echo "error: file 'docker-compose.yml' not found." >/dev/stderr
    exit 1
fi

${CMD} inspect --type=volume ubuntu-home >&/dev/null
if [ ! $? = 0 ]; then
    echo "Home volume not found, please run linux-setup before me." > /dev/stderr
    exit 1
fi

echo "starting..."
${CMD} compose up -d
echo "OK"
