#!/bin/sh

if [ -L $0 ]; then
    L=$(readlink $0)
    O=$(dirname $L)
    cd $O
else
    cd $(dirname $0)
fi
. config

if [ ! -f ./docker-compose.yml ]; then
    echo "file ./docker-compose.yml not found" > /dev/stderr
    exit 1
fi

echo "stopping..."
${CMD} compose stop
