#!/bin/sh

if [ -L $0 ]; then
    L=$(readlink $0)
    O=$(dirname $L)
    cd $O
else
    cd $(dirname $0)
fi
. config

while getopts a OPT; do
    case $OPT in
        a)
            ALL=1
            ;;
        *)
            echo "そのオプションは無効です: ${OPT}"
            exit 1;
            ;;
    esac
done

if [ ! "x$ALL" = "x" ]; then
    echo "reset home directory contents. OK?"
    read -p "Enter(OK)/Ctrl-C(cancel)>" yn
fi

# remove container
${CMD} compose down
if [ ! "x$ALL" = "x" ]; then
    for cmd in rm create; do
        ${CMD} volume ${cmd} ubuntu-home
    done
fi

echo "re-pulling image and create container"
${CMD} compose create --pull always

