#!/bin/bash
VOL=ubuntu-home
IMAGE=densukest/ubuntu-it-soft:v1
NAME=ubuntu
docker inspect --type=volume ${VOL} >& /dev/null

if [ ! $? = 0 ]; then
    echo "create volume ${VOL}"
    docker volume create --pull always "${VOL}"
fi

docker compose create --pull always
echo "OK: use command 'docker compose up -d' or script linux-start"

