#!/bin/bash

while getopts a OPT; do
    case $OPT in
        a)
            ALL=1
            ;;
        *)
            echo "そのオプションは無効です: ${OPT}"
            exit 1;
            ;;
    esac
done

if [ ! "x$ALL" = "x" ]; then
    echo "reset home directory contents. OK?"
    read -p "Enter(OK)/Ctrl-C(cancel)>" yn
fi

# remove container
docker compose down
if [ ! "x$ALL" = "x" ]; then
    for cmd in rm create; do
        docker volume ${cmd} ubuntu-home
    done
fi

echo "re-pulling image and create container"
docker compose create --pull always

